### PR TITLE
Remove S2S VPN limitation per gateway IP

### PR DESCRIPTION
**Pull request by resmo**

### CODE REVIEW

**Comment by resmo** [comment]
We see an issue after a VPC restart. After a VPC restart, only the last VPN will get established.

**Comment by remibergsma** [comment]
@resmo Thanks! At the moment we're ironing out small issues related to the CentOS 7 systemvm template. After that we'll look into other PRs :)

**Comment by resmo** [comment]
issue is unrelated, all fine.

**Comment by remibergsma** [comment]
@sanderv32 Can you please review this? Thx!

**Comment by remibergsma** [comment]
@resmo We recently merged significant changes to the systemvm (runs CentOS7 now) and surrounding java code, hence the delay. Could you rebase this with latest master and force-push it to this branch? When the build is then green we'll merge it. Thanks!

**Comment by sanderv32** [comment]
go build

**Comment by remibergsma** [comment]
This probably needs to be rebased with latest master to turn green

**Comment by resmo** [comment]
rebased

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
@resmo Thanks, looking good. Could you please remove `CLOUDSTACK-10077:` from the commit message, as we don't use these to track issues. Other than that it's good to go I'd say.

**Comment by resmo** [comment]
amended commit messages, rebased.

**Comment by sanderv32** [comment]
In Cosmic 6.0.x we changed to way how routerVM's are updating their configs. Because of this the config file gets overwritten with the last VPN which is configured. We need to modify this PR to get it working in Cosmic.

**Comment by sanderv32** [comment]
Created new PR #657 with modifications needed for Cosmic 6.x

**Pull request closed without merging**
