### PR TITLE
Format full code base

### PR DESCRIPTION
**Pull request by miguelaferreira**
Formatted and removed license headers in files:
- java
- python
- xml (except spring contexts)

Also removed the maven plugins that handle license header compliancy.

### CODE REVIEW

**Comment by borisroman** [comment]
@miguelaferreira The build was unsuccessful because the packaging was looking in the wrong directory for the jars. It happened because you moved the plugins back in..

**Comment by borisroman** [comment]
I got an error when starting this PR in my bubble

```
2016-06-27 08:07:50,525 WARN  [o.a.c.s.m.c.ResourceApplicationContext] (main:null) (logid:) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ipDeployersRegistry' defined in URL [jar:file:/root/.m2/repository/cloud/cosmic/cloud-nucleo/5.1.0.1-SNAPSHOT/cloud-nucleo-5.1.0.1-SNAPSHOT.jar!/META-INF/cloudstack/core/spring-core-registry-core-context.xml]: Cannot resolve reference to bean 'VpcVirtualRouter' while setting bean property 'preRegistered' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'VpcVirtualRouter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected org.cloud.network.router.deployment.RouterDeploymentDefinitionBuilder com.cloud.network.element.VirtualRouterElement.routerDeploymentDefinitionBuilder; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'routerDeploymentDefinitionBuilder': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.network.router.NetworkHelper org.cloud.network.router.deployment.RouterDeploymentDefinitionBuilder.nwHelper; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'networkHelper': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.network.NetworkModel com.cloud.network.router.NetworkHelperImpl._networkModel; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'networkModelImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.user.AccountManager com.cloud.network.NetworkModelImpl._accountMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'accountManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: public com.cloud.region.ha.GlobalLoadBalancingRulesService com.cloud.user.AccountManagerImpl._gslbService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GlobalLoadBalancingRulesServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.network.rules.RulesManager org.apache.cloudstack.region.gslb.GlobalLoadBalancingRulesServiceImpl._rulesMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rulesManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.network.IpAddressManager com.cloud.network.rules.RulesManagerImpl._ipAddrMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ipAddressManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.apache.cloudstack.engine.orchestration.service.NetworkOrchestrationService com.cloud.network.IpAddressManagerImpl._networkMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'networkOrchestrator': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.alert.AlertManager org.apache.cloudstack.engine.orchestration.NetworkOrchestrator._alertMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alertManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.storage.StorageManager com.cloud.alert.AlertManagerImpl._storageMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'storageManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.agent.AgentManager com.cloud.storage.StorageManagerImpl._agentMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusteredAgentManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.ha.HighAvailabilityManager com.cloud.agent.manager.AgentManagerImpl._haMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'highAvailabilityManagerExtImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.vm.VirtualMachineManager com.cloud.ha.HighAvailabilityManagerImpl._itMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'clusteredVirtualMachineManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.storage.dao.VMTemplateDao com.cloud.vm.VirtualMachineManagerImpl._templateDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'VMTemplateDaoImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.apache.cloudstack.storage.datastore.db.TemplateDataStoreDao com.cloud.storage.dao.VMTemplateDaoImpl._templateDataStoreDao; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateDataStoreDaoImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.apache.cloudstack.engine.subsystem.api.storage.DataStoreManager org.apache.cloudstack.storage.image.db.TemplateDataStoreDaoImpl._storeMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStoreProviderManager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.apache.cloudstack.storage.image.datastore.ImageStoreProviderManager org.apache.cloudstack.storage.datastore.provider.DataStoreProviderManagerImpl.imageStoreProviderMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'imageStoreProviderMgr': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.server.StatsCollector org.apache.cloudstack.storage.image.manager.ImageStoreProviderManagerImpl._statsCollector; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'statsCollector': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.cloud.vm.UserVmManager com.cloud.server.StatsCollector._userVmMgr; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userVmManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: com.cloud.network.router.VpcVirtualNetworkApplianceManager com.cloud.vm.UserVmManagerImpl._virtualNetAppliance; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vpcVirtualNetworkApplianceManagerImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected org.apache.cloudstack.network.topology.NetworkTopologyContext com.cloud.network.router.VirtualNetworkApplianceManagerImpl._networkTopologyContext; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'topologyContext': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.apache.cloudstack.network.topology.BasicNetworkTopology org.apache.cloudstack.network.topology.NetworkTopologyContext._basicNetworkTopology; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'basicNetworkTopology': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected org.apache.cloudstack.network.topology.BasicNetworkVisitor org.apache.cloudstack.network.topology.BasicNetworkTopology._basicVisitor; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'basicNetworkVisitor': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected com.cloud.network.router.NetworkHelper org.apache.cloudstack.network.topology.BasicNetworkVisitor._networkGeneralHelper; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [com.cloud.network.router.NetworkHelper] is defined: expected single matching bean but found 2: networkHelper,vpcNetworkHelper
```

**Comment by miguelaferreira** [comment]
Feel free to fix the error and push to this branch @borisroman

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
Build is green! :) https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/17/

**Pull request merged**
