### PR TITLE
Completely removes the management of device IDs by the management server

### PR DESCRIPTION
**Pull request by eliasgomes**
It fixes device ID conflicts when reallocating routers.

### CODE REVIEW

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Review by borisroman — CHANGES_REQUESTED** [review]
Verify order of nics attached to user instances.

**Comment by eliasgomes** [comment]
We did a little research, and based on `NetworkOrchestrator.java:624` we see that the default NIC always comes before the non-default ones. So the ordering isn't based on the device ID, therefore the behaviour won't change.

**Review by borisroman — APPROVED** [review]

**Pull request merged**
