### PR TITLE
Revert "Port apache/cloudstack#1533 that converts pacthviasocket to python"

### PR DESCRIPTION
**Pull request by remibergsma**
Reverts MissionCriticalCloud/cosmic#55

Works fine in Jenkins/Bubble but still leads to issues in our cloud environments. Reverting now, will look into the details later.

### CODE REVIEW

**Comment by remibergsma** [comment]
Ping @wilderrodrigues @bheuvel @miguelaferreira Please merge when green :-)

**Comment by remibergsma** [comment]
@wilderrodrigues @bheuvel Please see #65 for an alternate solution

**Comment by wilderrodrigues** [comment]
Hi @remibergsma I'm looking at it now.

**Comment by wilderrodrigues** [comment]
This one failed and the other one is still building. Will have a look around 0530 to see if that's done. If that's green, can I merge it?

**Pull request closed without merging**
