### PR TITLE
Block VPN ports on all public IPs when no VPN configured

### PR DESCRIPTION
**Pull request by RobbertJanSW**

### CODE REVIEW

**Comment by remibergsma** [comment]
Thanks for the PR @RobbertJanSW! Did you by any chance check #809? That was supposed to fix the same problem (available on VPCs after a cleanup to a 19.1.x VPC route version). Would be nice if you can confirm whether or not the problem you want to fix still exists with this PR (and post some results).  Thanks!

**Comment by RobbertJanSW** [comment]
Yes, definitely. #809 fixes the issue for 1 public IP, not for all of them. It only creates DROP rules for `interface['ipv4_addresses'][0]['cidr']` (check line 41 in #809 ). Not for all public IPs on that public interface.

Unless something else goes wrong and we dont want to listen to UDP/500 on all public IPs. In which case we should be fixing this elsewhere..

**Comment by remibergsma** [comment]
It is supposed to allow the first ip (source nat aka where VPN is only configured) and also reject it for all others by the use of `!` on the source nat ip (so you don't need to list all ips). Will PM you to ask for a setup where this is not sufficient so we can have a look.

**Comment by RobbertJanSW** [comment]
We do not use VPN on the routers that end up with the UDP/500 port open. So `vpn_open` is false (Line 47-58). Then, line 60-63 is only hit once with one specific `public_ip` (the IP `public_ip = interface['ipv4_addresses'][0]['cidr']` from line 41), finally default-blocking only 1 public IP in `block_vpn_rules`.

**Pull request merged**
