### PR TITLE
Align maven dependencies.

### PR DESCRIPTION
**Pull request by borisroman**

### CODE REVIEW

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
[Jenkins build #35](https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/35/) failed on [0600-collect-artifacts-and-cleanup/31](https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0600-collect-artifacts-and-cleanup/31/console):

```
20:28:27 ==> Collecting Management Server Logs and Code Coverage Report
20:28:28 scp: /var/log/cosmic/management/*.log*: No such file or directory
20:28:28 Build step 'Execute shell' marked build as failure
```

[Jenkins build/#37](https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/37/) failed on [0500-run-integration-tests/37](https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0500-run-integration-tests/37/console):

```
11:46:33 [INFO] 2016-06-29 11:46:52,560 - marvin - === Test Client Creation Successful ===
11:46:33 [INFO] 2016-06-29 11:46:52,560 - marvin - === Marvin Init Successful ===
11:46:33 [CRITICAL] 2016-06-29 11:46:52,562 - marvin - EXCEPTION: Failure:: (<type 'exceptions.TypeError'>, TypeError('sequence item 0: expected string, NoneType found',), <traceback object at 0x3b14b00>)
11:46:33 [INFO] 2016-06-29 11:46:52,562 - marvin - === TestName: Failure: | Status : EXCEPTION ===
11:46:33 [INFO] 2016-06-29 11:46:52,564 - marvin - === finalize does nothing!  ===
11:46:33 + true
11:46:33 Started calculate disk usage of build
```

Tested in a bubble, and gets successfully into integration tests...

Started next attempt on [Jenkins build #38](https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/38/)

**Comment by bheuvel** [comment]
```
Jun 29 13:51:32 cs1 server: log4j:ERROR Could not create an Appender. Reported error follows.
Jun 29 13:51:32 cs1 server: java.lang.ClassNotFoundException: org.apache.log4j.rolling.RollingFileAppender
```

It's missing `apache-log4j-extras-1.2.17.jar` despite the entry in the pom? [pom.xml#L327](https://github.com/MissionCriticalCloud/cosmic/blob/tmp/mvn_deps2/pom.xml#L327):

```
            <dependency>
                <groupId>log4j</groupId>
                <artifactId>apache-log4j-extras</artifactId>
                <version>${cs.apache-log4j-extras.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>log4j</artifactId>
                        <groupId>log4j</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
```

```
[root@cs1 lib]# ls -als *log4j*
480 -rw-r--r--. 1 tomcat tomcat 489884 Jun 13 11:10 log4j-1.2.17.jar
 12 -rw-r--r--. 1 tomcat tomcat   9988 Jun 14 12:52 slf4j-log4j12-1.7.21.jar
```

(Manually) Verified adding `apache-log4j-extras-1.2.17.jar` makes it work...

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Pull request merged**
