### PR TITLE
adding field cosmic to list capabilities

### PR DESCRIPTION
**Pull request by ddegoede**
adding field cosmic to list capabilities so we can distinguish between CS and Cosmic in e.g. terraform

### CODE REVIEW

**Comment by remibergsma** [comment]
Looks like this:

```
(bubble) > list capabilities 
capability:
allowusercreateprojects = True
allowuserexpungerecovervm = True
allowuserviewdestroyedvm = True
cloudstackversion = 5.1.0.13-SNAPSHOT
cosmic = True
customdiskofferingmaxsize = 1024
customdiskofferingminsize = 1
kvmsnapshotenabled = False
projectinviterequired = False
regionsecondaryenabled = False
securitygroupsenabled = False
supportELB = false
userpublictemplateenabled = True
```

**Comment by remibergsma** [comment]
Go build

**Comment by remibergsma** [comment]
Go build

**Comment by remibergsma** [comment]
Go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
Go build

**Review by borisroman — APPROVED** [review]

**Pull request merged**
