### PR TITLE
Stability fixes for CentOS7 based systemvm

### PR DESCRIPTION
**Pull request by remibergsma**
This requires the latest `systemvm` template from Jenkins with this PR included: https://github.com/MissionCriticalCloud/systemvm-packer/pull/36

This PR requires this `bubble-toolkit` PR:
https://github.com/MissionCriticalCloud/bubble-toolkit/pull/264

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
PR was green, running one more time

**Comment by remibergsma** [comment]
The "random" SSH errors happen because "sometimes" the VM doesn't get its ip-address, hence SSH doesn't work. A `dhclient eth0` fixes it, so it seems timing related. Investigating.

**Comment by remibergsma** [comment]
It doesn't happen often though, I had to loop the `test_vpc_redundant.py` tests for more than 6 hours before I saw it going wrong and could investigate what is wrong. That's also why this PR is green again now.

**Comment by remibergsma** [comment]
In some cases the `macchina` VM boots faster than the network of the rVPC is configured and hence does not get an ip address. We should use is_persistent=true to have networks be created before VMs are deployed.

```
MariaDB [cloud]> select name,is_persistent from network_offerings;
+--------------------------------------------------------------+---------------+
| name                                                         | is_persistent |
+--------------------------------------------------------------+---------------+
| System-Public-Network                                        |             0 |
| System-Management-Network                                    |             0 |
| System-Control-Network                                       |             0 |
| System-Storage-Network                                       |             0 |
| DefaultPrivateGatewayNetworkOffering                         |             1 |
| DefaultPrivateGatewayNetworkOfferingSpecifyVlan              |             1 |
| DefaultSharedNetworkOfferingWithSGService                    |             1 |
| DefaultSharedNetworkOffering                                 |             1 |
| DefaultIsolatedNetworkOfferingWithSourceNatService           |             1 |
| DefaultIsolatedNetworkOffering                               |             1 |
| DefaultIsolatedNetworkOfferingWithEgress                     |             1 |
| DefaultRedundantIsolatedNetworkOffering                      |             1 |
| DefaultRedundantIsolatedNetworkOfferingWithEgress            |             1 |
| DefaultIsolatedNetworkOfferingForVpcNetworks                 |             1 |
| DefaultIsolatedNetworkOfferingForVpcNetworksNoLB             |             1 |
| DefaultIsolatedNetworkOfferingForVpcNetworksWithInternalLB   |             1 |
| DefaultIsolatedNetworkOfferingForVpcNetworksWithoutSourceNat |             1 |
| DefaultIsolatedNetworkOfferingForVpcNetworksInternalVPC      |             1 |
+--------------------------------------------------------------+---------------+
18 rows in set (0.01 sec)
```

**Comment by remibergsma** [comment]
The failures with "wrong number of routers" was because part of the tests used the API to query and some directly queried the router. In some rare cases (took me 8 hours to run into it in a loop) the state from the router doesn't match the DB (yet) as that one is updated every 30 seconds. The test sleeps 14 seconds and that wasn't always enough. I changed the 30 second check run by the management server to 5 seconds (changed global setting) to have a way faster sync of the state of the router.

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
PR was green now, re-testing.

**Comment by borisroman** [comment]
Green 🎉

**Comment by remibergsma** [comment]
I'll kick Jenkins once more and also have the tests that failed running in a loop over night. Tomorrow I'll check the results. Once it's fine, I'll clean the commits in the PR. We're getting there :) 💯

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Pull request merged**
