### PR TITLE
Update dependency versions to latest where possible

### PR DESCRIPTION
**Pull request by bheuvel**
Includes/closes separate "test" PRs:
Closes #377 
Closes #378 
Closes #379 
Closes #380 
Closes #381 
Closes #382 
Closes #383

Closes PR for removal of Batik, but retains it as it seems to be required;
Not "explicitly" defined; runtime dependency (for Cosmic-Agent) 
Closes #384

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/1227/

Failed on:
 integration.smoke.test_release_ip.TestReleaseIP.test_01_release_ip
 integration.smoke.test_router_dhcphosts.TestRouterDHCPHosts.test_01_router_dhcphosts
 <nose.suite.ContextSuite context=TestRouterDHCPHosts>:teardown

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
go build

**Pull request merged**
