### PR TITLE
Limit DNS usage to internal tiers only

### PR DESCRIPTION
**Pull request by remibergsma**
Backport fix to prevent DNS reflection attacks.

### CODE REVIEW

**Comment by remibergsma** [comment]
I think we hit this problem only in specific cases, like when the tier is publicly exposed somehow. Maybe in basic networking? It seems to be fine on the advanced networking.

**Comment by miguelaferreira** [comment]
To be merged @remibergsma?

**Comment by wilderrodrigues** [comment]
@remibergsma @bheuvel can we merge this?

**Comment by remibergsma** [comment]
@wilderrodrigues Thanks dude, this one is ready indeed!

**Pull request merged**
