### PR TITLE
Remove checkstyle and scm config from maven

### PR DESCRIPTION
**Pull request by miguelaferreira**
Some of the modules still had the scm tag pointing to the old submodule repos, I've removed that.
I've also removed the checkstyle configuration since we need to adjust it.

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Pull request merged**
