### PR TITLE
Add compliance metadata and API for VMs and VPCs

### PR DESCRIPTION
**Pull request by rarenerd**
Expands on the existing dashboard to mark VMs and VPCs as needing a
restart, and showing this in their respective overviews.

- Add compliance status as metadata to VMs and VPCs, with compliant or
needs restart states
- Clear the status on restart of VMs and VPCs
- Update unit tests
- Update API to allow setting and retrieving the compliance status
- Add state to UI in VM and VPC overviews
- Add filter for VMs needing a restart

Screenshots:
VM overview
Screenshot 2020-05-29 at 17 15 46

VM filter
Screenshot 2020-05-29 at 17 15 58

VPC overview
Screenshot 2020-05-29 at 17 16 07

Dashboard
Screenshot 2020-05-29 at 17 15 28

### CODE REVIEW

**Comment by rarenerd** [comment]
go build

**Comment by ddegoede** [comment]
go build

**Comment by ddegoede** [comment]
go build

**Comment by ddegoede** [comment]
go build

**Comment by rarenerd** [comment]
go build

**Comment by rarenerd** [comment]
go build

**Comment by remibergsma** [comment]
This closes #868

Looks good to me @rarenerd, great work 👍

**Pull request merged**
