### PR TITLE
KVM Feature: Live VM migration with storage

### PR DESCRIPTION
**Pull request by eliasgomes**

### CODE REVIEW

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
Looks pretty clean. I'll try to break it. Maybe we can already think about what happens when we migrate from localstorage to localstorage.

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
Needed to update the POMs to the include the correct version of cloud-engine-storage-datamotion.

**Pull request merged**
