### PR TITLE
Use methods from the common class, update test_ip_exclusion_list.py

### PR DESCRIPTION
**Pull request by borisroman**

### CODE REVIEW

**Comment by borisroman** [comment]
Separated tests work fine: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/1032/

**Comment by borisroman** [comment]
When this is merged, this PR can go in: https://github.com/MissionCriticalCloud/organization_utils/pull/108

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
go build

**Pull request merged**
