### PR TITLE
Make stopVirtualMachine use the force parameter

### PR DESCRIPTION
**Pull request by remibergsma**
Backport of ACS

### CODE REVIEW

**Comment by remibergsma** [comment]
Go build

**Comment by remibergsma** [comment]
Tested on KVM, after ~2min when the VM cannot shutdown (I removed several binaries and config scripts so it couldn't do it), it was forcefully stopped.

**Comment by miguelaferreira** [comment]
Shall I  merge @remibergsma?

**Comment by wilderrodrigues** [comment]
this one as well, @remibergsma ?

**Comment by remibergsma** [comment]
Let me verify on XenServer (building a setup as we speak). Will let you know soon..

**Comment by remibergsma** [comment]
Tested and verified that stopping without force still results in a proper shutdown. Then also verified that force=true results in an immediate shutdown of the VM (it didn't try to be nice first, like KVM).

Anyway, good to be merged @bheuvel @miguelaferreira @wilderrodrigues

**Pull request merged**
