### PR TITLE
Fix assigning affinity group with router deployments enabled

### PR DESCRIPTION
**Pull request by remibergsma**

### CODE REVIEW

**Comment by remibergsma** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Pull request merged**
