### PR TITLE
Configure system vms with a list of available management server IPs

### PR DESCRIPTION
**Pull request by miguelaferreira**

### CODE REVIEW

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
@miguelaferreira It failed due to two things;
1. A couple tests failed.
2. It couldn't retrieve the management log from the cs1 box.

The latter is because the log was in the tomcat home directory.

```
[root@cs1 ~]# cd ~tomcat/
[root@cs1 tomcat]# ls -la
total 135376
drwxrwxr-x.   5 root   tomcat      4096 Aug  5 14:38 .
drwxr-xr-x. 108 root   root        4096 Aug  5 14:30 ..
drwxr-xr-x.   2 root   root        4096 Aug  5 14:30 bin
lrwxrwxrwx.   1 root   tomcat        11 Aug  5 14:30 conf -> /etc/tomcat
drwxr-xr-x.   2 root   root        4096 Aug  5 14:38 db
lrwxrwxrwx.   1 root   tomcat        22 Aug  5 14:30 lib -> /usr/share/java/tomcat
lrwxrwxrwx.   1 root   tomcat        15 Aug  5 14:30 logs -> /var/log/tomcat
-rw-r--r--.   1 tomcat tomcat 138604492 Aug  5 18:02 management.log
drwx------.   2 tomcat tomcat      4096 Aug  5 14:38 .ssh
lrwxrwxrwx.   1 root   tomcat        22 Aug  5 14:30 temp -> /var/cache/tomcat/temp
lrwxrwxrwx.   1 root   tomcat        23 Aug  5 14:30 webapps -> /var/lib/tomcat/webapps
lrwxrwxrwx.   1 root   tomcat        22 Aug  5 14:30 work -> /var/cache/tomcat/work
```

```
[root@cs1 tomcat]# cd /var/log/cosmic/management/
[root@cs1 management]# ls -la
total 8
drwxr-xr-x. 2 tomcat root 4096 Aug  5 14:38 .
drwxr-xr-x. 3 tomcat root 4096 Aug  5 14:38 ..
```

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
Several tests now failed sending a `listZones` command, seems like a glitch and, therefore, I'll restart the build.

go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
Final integration test failing because of an error downloading a template

``` python
Stacktrace

  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/data/jenkins-slave/workspace/cosmic/0002-cosmic-pull-request-build/cosmic-core/test/integration/smoke/test_vpc_vpn.py", line 450, in setUpClass
    cls.template.download(cls.apiclient)
  File "/usr/lib/python2.7/site-packages/marvin/lib/base.py", line 1286, in download
    template.status)
'Error in downloading template
```

**Pull request merged**
