### PR TITLE
Collect test coverage report from KVM agents

### PR DESCRIPTION
**Pull request by miguelaferreira**
This PR needs two other PRs, so please merge those first:
- MissionCriticalCloud/organization_utils#74
- MissionCriticalCloud/bubble-toolkit#154

### CODE REVIEW

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
@miguelaferreira IT'S GREEN! FINALLY!!

**Comment by miguelaferreira** [comment]
SUPER!!

**Pull request merged**
