### PR TITLE
[WIP] Remove esapi

### PR DESCRIPTION
**Pull request by bheuvel**
Separate PR for better testing. Joining later into #372

### CODE REVIEW

**Comment by bheuvel** [comment]
first build failed:
```
18:59:22 CloudstackAPIException: Execute cmd: addhost failed, due to: errorCode: 530, errorText:Unable to add the host
```
https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/1216/

**Comment by bheuvel** [comment]
go build

**Comment by bheuvel** [comment]
second build failed:
```
21:28:35 CloudstackAPIException: Execute cmd: addhost failed, due to: errorCode: 530, errorText:Unable to add the host
```
https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0020-full-build/1682/

**Comment by bheuvel** [comment]
Third build failed:
https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/1230/

Failed on:
test_password_server.TestPasswordService.test_02_vpc_password_service_redundant_vpc
test_release_ip.TestReleaseIP.test_01_release_ip
test_router_rules.TestRouterRules.test_01_network_rules_acquired_public_ip_1_static_nat_rule
test_router_rules.TestRouterRules.test_01_network_rules_acquired_public_ip_2_nat_rule
test_router_rules.TestRouterRules.test_01_network_rules_acquired_public_ip_3_Load_Balancer_Rule

**Comment by bheuvel** [comment]
Fourth build failed on setup-infra

**Comment by bheuvel** [comment]
go build

**Comment by remibergsma** [comment]
go build (settup infra was running for over a day. Killed it)

**Pull request closed without merging**
