### PR TITLE
Fix default gw on non-default networks

### PR DESCRIPTION
**Pull request by remibergsma**
Backport of PR 1766 of ACS

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
We most likely need to investigate the test failures, as they seem to be consitent

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
This fixes #7

**Pull request merged**
