### PR TITLE
Set retries for VPN connections to forever

### PR DESCRIPTION
**Pull request by remibergsma**
Set retries for VPN connections to forever

### CODE REVIEW

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by remibergsma** [comment]
@miguelaferreira FYI: Marvin run into an exception, although it still reported SUCCESS. No integration tests were run: https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0500-run-integration-tests/224/console

**Comment by miguelaferreira** [comment]
The integration tests job does not break the build, otherwise the subsequent steps would not run. It is the failed test report that breaks it (at the end). We need to make the absence of a report also break it.

**Comment by miguelaferreira** [comment]
The exception initialising marvin has to do with missing test cases to run. Somehow the `${tests}` did not get expanded.

**Comment by miguelaferreira** [comment]
The `${tests}` parameter was not defined in the PR job. Let's try again: go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by miguelaferreira** [comment]
The integration tests results were not published in Jenkins because if a misconfiguration of the job, I've checked the logs and couldn't find a test with FAILURE of EXCEPTION status. 👍

**Pull request merged**
