### PR TITLE
Add logging to iptables on the VPC router

### PR DESCRIPTION
**Pull request by borisroman**
WIP Don't merge yet!

### CODE REVIEW

**Comment by borisroman** [comment]
go build

**Comment by wilderrodrigues** [comment]
go build

**Comment by wilderrodrigues** [comment]
Ping @borisroman : could you please rebase this PR so the tests can run fine?

**Comment by remibergsma** [comment]
Rebased with current master

**Comment by remibergsma** [comment]
Probably we still see some test failures. We need to add egress rules to the tests because an issue was fixed that missed a default drop.

**Comment by ddegoede** [comment]
Please do not merge even if it successfully builds, as this will break customers that are not aware they are missing firewall rules

We are planning to make an intermediate build with LOG instead of DROP, prior to deploying the DROP build.

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
This PR was supposed to fix the missing Egress DENY rules. However, the first step to be able to fix this in running environments, is to have proper logging of what would be blocked. This PR adds this logging. The logging is discarded by default and can be enabled by changing `00-iptables.conf` on a case-by-case basis. PR #67 was created to add the DENY Egress rule, when we're ready.

**Pull request merged**
