### PR TITLE
Add service group to api calls

### PR DESCRIPTION
**Pull request by ddegoede**
This PR adds a service group field to all API commands, so listApis will return this group for automatic generation of API doc and API clients.

Both name and group are mandatory for all API commands.

### CODE REVIEW

**Comment by eliasgomes** [comment]
I would either create constants or enumerations for the group strings.

**Comment by ddegoede** [comment]
List of group names and group description

```
LoadBalancerService,"Load Balancer"
AccountService,"Account"
AffinityService,"Affinity"
AlertService,"Alert"
AsyncjobService,"Async job"
AuthenticationService,"Authentication"
AutoScaleService,"AutoScale"
CertificateService,"Certificate"
CloudOpsService,"CloudOps"
ClusterService,"Cluster"
ConfigurationService,"Configuration"
DiskOfferingService,"Disk Offering"
DomainService,"Domain"
EventService,"Event"
FirewallService,"Firewall"
GuestOSService,"Guest OS"
HostService,"Host"
HypervisorService,"Hypervisor"
ImageStoreService,"Image Store"
InternalLBService,"Internal LB"
ISOService,"ISO"
LimitService,"Limit"
LoadBalancerService,"Load Balancer"
NATService,"NAT"
NetworkACLService,"Network ACL"
NetworkDeviceService,"Network Device"
NetworkOfferingService,"Network Offering"
NetworkService,"Network"
NiciraNVPService,"Nicira NVP"
NicService,"Nic"
PodService,"Pod"
PortableIPService,"Portable IP"
ProjectService,"Project"
PublicIPAddressService,"Public IP Address"
RegionService,"Region"
ResourcemetadataService,"Resource metadata"
ResourcetagsService,"Resource tags"
RouterService,"Router"
SecurityGroupService,"Security Group"
ServiceOfferingService,"Service Offering"
SnapshotService,"Snapshot"
SSHService,"SSH"
StoragePoolService,"Storage Pool"
SwiftService,"Swift"
SystemService,"System"
SystemVMService,"System VM"
TemplateService,"Template"
UsageService,"Usage"
UserService,"User"
VirtualMachineService,"Virtual Machine"
VLANService,"VLAN"
VMGroupService,"VM Group"
VolumeService,"Volume"
VPCService,"VPC"
VPNService,"VPN"
ZoneService,"Zone"
BaseCmdTestService,"BaseCmdTest"
```

**Comment by ddegoede** [comment]
List of groups and associated API commands:

```
LoadBalancerService
   createLoadBalancerRule
   deleteLoadBalancerRule
   removeFromLoadBalancerRule
   assignToLoadBalancerRule
   createLBStickinessPolicy
   updateLBStickinessPolicy
   deleteLBStickinessPolicy
   listLoadBalancerRules
   listLBStickinessPolicies
   listLBHealthCheckPolicies
   createLBHealthCheckPolicy
   updateLBHealthCheckPolicy
   deleteLBHealthCheckPolicy
   listLoadBalancerRuleInstances
   updateLoadBalancerRule
   uploadSslCert
   deleteSslCert
   listSslCerts
   assignCertToLoadBalancer
   removeCertFromLoadBalancer
   createGlobalLoadBalancerRule
   deleteGlobalLoadBalancerRule
   updateGlobalLoadBalancerRule
   listGlobalLoadBalancerRules
   assignToGlobalLoadBalancerRule
   removeFromGlobalLoadBalancerRule
   createLoadBalancer
   listLoadBalancers
   deleteLoadBalancer
   updateLoadBalancer
NetworkService
   dedicatePublicIpRange
   releasePublicIpRange
   createNetwork
   deleteNetwork
   listNetworks
   restartNetwork
   updateNetwork
   createPhysicalNetwork
   deletePhysicalNetwork
   listPhysicalNetworks
   updatePhysicalNetwork
   listSupportedNetworkServices
   addNetworkServiceProvider
   deleteNetworkServiceProvider
   listNetworkServiceProviders
   updateNetworkServiceProvider
   createStorageNetworkIpRange
   deleteStorageNetworkIpRange
   listStorageNetworkIpRange
   updateStorageNetworkIpRange
   listNiciraNvpDeviceNetworks
   listNetworkIsolationMethods
VirtualMachineService
   deployVirtualMachine
   destroyVirtualMachine
   rebootVirtualMachine
   startVirtualMachine
   stopVirtualMachine
   resetPasswordForVirtualMachine
   updateVirtualMachine
   listVirtualMachines
   getVMPassword
   restoreVirtualMachine
   changeServiceForVirtualMachine
   scaleVirtualMachine
   assignVirtualMachine
   migrateVirtualMachine
   migrateVirtualMachineWithVolume
   recoverVirtualMachine
   expungeVirtualMachine
   cleanVMReservations
   addNicToVirtualMachine
   removeNicFromVirtualMachine
   updateDefaultNicForVirtualMachine
VPNService
   createRemoteAccessVpn
   deleteRemoteAccessVpn
   listRemoteAccessVpns
   updateRemoteAccessVpn
   addVpnUser
   removeVpnUser
   listVpnUsers
   createVpnCustomerGateway
   createVpnGateway
   createVpnConnection
   deleteVpnCustomerGateway
   deleteVpnGateway
   deleteVpnConnection
   updateVpnCustomerGateway
   resetVpnConnection
   listVpnCustomerGateways
   listVpnGateways
   listVpnConnections
   updateVpnConnection
   updateVpnGateway
AutoScaleService
   createCounter
   createCondition
   createAutoScalePolicy
   createAutoScaleVmProfile
   createAutoScaleVmGroup
   deleteCounter
   deleteCondition
   deleteAutoScalePolicy
   deleteAutoScaleVmProfile
   deleteAutoScaleVmGroup
   listCounters
   listConditions
   listAutoScalePolicies
   listAutoScaleVmProfiles
   listAutoScaleVmGroups
   enableAutoScaleVmGroup
   disableAutoScaleVmGroup
   updateAutoScalePolicy
   updateAutoScaleVmProfile
   updateAutoScaleVmGroup
VPCService
   createVPC
   listVPCs
   deleteVPC
   updateVPC
   restartVPC
   createVPCOffering
   updateVPCOffering
   deleteVPCOffering
   listVPCOfferings
   createPrivateGateway
   listPrivateGateways
   deletePrivateGateway
   createStaticRoute
   deleteStaticRoute
   listStaticRoutes
UsageService
   addTrafficType
   deleteTrafficType
   listTrafficTypes
   updateTrafficType
   listTrafficTypeImplementors
   generateUsageRecords
   listUsageRecords
   listUsageTypes
   removeRawUsageRecords
   addTrafficMonitor
   deleteTrafficMonitor
   listTrafficMonitors
TemplateService
   createTemplate
   registerTemplate
   updateTemplate
   copyTemplate
   deleteTemplate
   listTemplates
   updateTemplatePermissions
   listTemplatePermissions
   extractTemplate
   prepareTemplate
   upgradeRouterTemplate
   getUploadParamsForTemplate
HostService
   addHost
   reconnectHost
   updateHost
   deleteHost
   prepareHostForMaintenance
   cancelHostMaintenance
   listHosts
   listHostTags
   findHostsForMigration
   addSecondaryStorage
   updateHostPassword
   releaseHostReservation
   dedicateHost
   listDedicatedHosts
   releaseDedicatedHost
FirewallService
   listPortForwardingRules
   createPortForwardingRule
   deletePortForwardingRule
   updatePortForwardingRule
   createFirewallRule
   deleteFirewallRule
   listFirewallRules
   updateFirewallRule
   createEgressFirewallRule
   deleteEgressFirewallRule
   listEgressFirewallRules
   updateEgressFirewallRule
VolumeService
   attachVolume
   uploadVolume
   detachVolume
   createVolume
   deleteVolume
   listVolumes
   extractVolume
   migrateVolume
   resizeVolume
   updateVolume
   getUploadParamsForVolume
AccountService
   createAccount
   deleteAccount
   updateAccount
   disableAccount
   enableAccount
   lockAccount
   listAccounts
   markDefaultZoneForAccount
   addAccountToProject
   deleteAccountFromProject
   listProjectAccounts
UserService
   createUser
   deleteUser
   updateUser
   listUsers
   lockUser
   disableUser
   enableUser
   getUser
   getVirtualMachineUserData
   registerUserKeys
SnapshotService
   createSnapshot
   listSnapshots
   deleteSnapshot
   createSnapshotPolicy
   updateSnapshotPolicy
   deleteSnapshotPolicies
   listSnapshotPolicies
   revertSnapshot
   listVMSnapshot
   createVMSnapshot
   deleteVMSnapshot
   revertToVMSnapshot
   createSnapshotFromVMSnapshot
ISOService
   attachIso
   detachIso
   listIsos
   registerIso
   updateIso
   deleteIso
   copyIso
   updateIsoPermissions
   listIsoPermissions
   extractIso
RouterService
   startRouter
   rebootRouter
   stopRouter
   destroyRouter
   changeServiceForRouter
   listRouters
   listVirtualRouterElements
   configureVirtualRouterElement
   createVirtualRouterElement
ProjectService
   createProject
   deleteProject
   updateProject
   activateProject
   suspendProject
   listProjects
   listProjectInvitations
   updateProjectInvitation
   deleteProjectInvitation
NetworkACLService
   createNetworkACL
   updateNetworkACLItem
   deleteNetworkACL
   listNetworkACLs
   createNetworkACLList
   deleteNetworkACLList
   replaceNetworkACLList
   listNetworkACLLists
   updateNetworkACLList
GuestOSService
   listOsTypes
   listOsCategories
   addGuestOs
   updateGuestOs
   removeGuestOs
   listGuestOsMapping
   addGuestOsMapping
   updateGuestOsMapping
   removeGuestOsMapping
SystemVMService
   startSystemVm
   rebootSystemVm
   stopSystemVm
   destroySystemVm
   listSystemVms
   migrateSystemVm
   changeServiceForSystemVm
   scaleSystemVm
ImageStoreService
   addImageStore
   addImageStoreS3
   listImageStores
   deleteImageStore
   createSecondaryStagingStore
   listSecondaryStagingStores
   deleteSecondaryStagingStore
   updateCloudToUseObjectStore
SecurityGroupService
   createSecurityGroup
   deleteSecurityGroup
   authorizeSecurityGroupIngress
   revokeSecurityGroupIngress
   authorizeSecurityGroupEgress
   revokeSecurityGroupEgress
   listSecurityGroups
VLANService
   createVlanIpRange
   deleteVlanIpRange
   listVlanIpRanges
   dedicateGuestVlanRange
   releaseDedicatedGuestVlanRange
   listDedicatedGuestVlanRanges
InternalLBService
   configureInternalLoadBalancerElement
   createInternalLoadBalancerElement
   listInternalLoadBalancerElements
   stopInternalLoadBalancerVM
   startInternalLoadBalancerVM
   listInternalLoadBalancerVMs
SSHService
   resetSSHKeyForVirtualMachine
   registerSSHKeyPair
   createSSHKeyPair
   deleteSSHKeyPair
   listSSHKeyPairs
NATService
   enableStaticNat
   createIpForwardingRule
   deleteIpForwardingRule
   listIpForwardingRules
   disableStaticNat
DomainService
   createDomain
   updateDomain
   deleteDomain
   listDomains
   listDomainChildren
AffinityGroupService
   createAffinityGroup
   deleteAffinityGroup
   listAffinityGroups
   updateVMAffinityGroup
   listAffinityGroupTypes
ZoneService
   createZone
   updateZone
   deleteZone
   listZones
   dedicateZone
   listDedicatedZones
   releaseDedicatedZone
VMGroupService
   createInstanceGroup
   deleteInstanceGroup
   updateInstanceGroup
   listInstanceGroups
ServiceOfferingService
   createServiceOffering
   deleteServiceOffering
   updateServiceOffering
   listServiceOfferings
ResourcetagsService
   listStorageTags
   createTags
   deleteTags
   listTags
RegionService
   addRegion
   updateRegion
   removeRegion
   listRegions
PodService
   createPod
   updatePod
   deletePod
   listPods
   dedicatePod
   listDedicatedPods
   releaseDedicatedPod
NicService
   addIpToNic
   removeIpFromNic
   updateVmNicIp
   listNics
NetworkOfferingService
   createNetworkOffering
   updateNetworkOffering
   deleteNetworkOffering
   listNetworkOfferings
EventService
   listEvents
   listEventTypes
   archiveEvents
   deleteEvents
DiskOfferingService
   createDiskOffering
   updateDiskOffering
   deleteDiskOffering
   listDiskOfferings
ConfigurationService
   updateConfiguration
   listConfigurations
   listCapabilities
   listDeploymentPlanners
ClusterService
   addCluster
   deleteCluster
   updateCluster
   listClusters
   dedicateCluster
   listDedicatedClusters
   releaseDedicatedCluster
AlertService
   listAlerts
   archiveAlerts
   deleteAlerts
   generateAlert
AddressService
   associateIpAddress
   disassociateIpAddress
   listPublicIpAddresses
   updateIpAddress
StoragePoolService
   listStoragePools
   createStoragePool
   updateStoragePool
   deleteStoragePool
   findStoragePoolsForMigration
   listStorageProviders
   enableStorageMaintenance
   cancelStorageMaintenance
ResourcemetadataService
   addResourceDetail
   removeResourceDetail
   listResourceDetails
PortableIPService
   createPortableIpRange
   deletePortableIpRange
   listPortableIpRanges
NiciraNVPService
   addNiciraNvpDevice
   deleteNiciraNvpDevice
   listNiciraNvpDevices
NetworkDeviceService
   addNetworkDevice
   listNetworkDevice
   deleteNetworkDevice
LimitService
   updateResourceLimit
   updateResourceCount
   listResourceLimits
   resetApiLimit
   getApiLimit
HypervisorService
   listHypervisors
   updateHypervisorCapabilities
   listHypervisorCapabilities
SwiftService
   addSwift
   listSwifts
AuthenticationService
   login
   logout
   linkDomainToLdap
   importLdapUsers
   listLdapConfigurations
   ldapCreateAccount
   addLdapConfiguration
   ldapConfig
   listDomainLdapLink
   deleteLdapConfiguration
   searchLdap
   ldapRemove
   listLdapUsers
AsyncjobService
   queryAsyncJobResult
   listAsyncJobs
SystemService
   listCapacity
   getCloudIdentifier
   listApis
CertificateService
   uploadCustomCertificate
CloudOps
   listHAWorkers
   listWhoHasThisMac
   listWhoHasThisIp
BaseCmdTest
   BaseCmdTest.CMD1_NAME
   BaseCmdTest.CMD2_NAME
```

**Comment by ddegoede** [comment]
@eliasgomes @remibergsma @borisroman I added the proposed groupnames and grouping, please let me know If you agree with this grouping?

@remibergsma, one of the differences between this list and the one we composed on tuesday, is that I moved the `dedicate` commands from affinity to their more specific group, e.g.  `dedicateCluster` now falls under `ClusterService`, but is open for debate.

If you agree with this grouping, @eliasgomes and me will create the `enumeration` for these groups with a name and description property, the name will be useful for API clients, and the description will be useful for documentation, e.g. APIDOC.

**Comment by ddegoede** [comment]
Filtered output of the list apis:
```(local) üêµ > list apis name=deployVirtualMachine filter=name,groupname,groupdescription
{
  "api": [
    {
      "groupdescription": "Virtual Machine",
      "groupname": "VirtualMachineService",
      "name": "deployVirtualMachine"
    }
  ],
  "count": 1
}```

**Pull request merged**
