### PR TITLE
Fix router deployment when two threads try to start it simultaneously

### PR DESCRIPTION
**Pull request by remibergsma**
Backport of ACS PR 1870

### CODE REVIEW

**Comment by remibergsma** [comment]
go build

**Comment by eliasgomes** [comment]
go build

**Comment by eliasgomes** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
@remibergsma This doesn't seem to be working very well...

https://beta-jenkins.mcc.schubergphilis.com/job/cosmic/job/0002-cosmic-pull-request-build/741/

image

**Comment by borisroman** [comment]
go build

**Comment by borisroman** [comment]
Running it again to verify.

**Comment by remibergsma** [comment]
It's clear we should not backport this PR ;-) Closing now.

**Pull request closed without merging**
