### PR TITLE
Remove engine maven module and flatten submodules 

### PR DESCRIPTION
**Pull request by miguelaferreira**
I've flatten the submodules and removed the engine module pom, but also delete unused code, and removed some duplicated blocks.

### CODE REVIEW

**Comment by miguelaferreira** [comment]
Go build

**Comment by miguelaferreira** [comment]
@borisroman if build goes well could you please improve commit 2cd82e3. I mean give it a better title, or squash it with something else. If the reason is to remove duplication, just say that, or whatever provides a commit history-level context (not easy I know 😉).

My guess (because I did extract that same method at some point) is that the code is duplicated, but I don't see where is the new method being applied elsewhere. Am I missing something?

**Comment by miguelaferreira** [comment]
Integration test failed due to a (recurring) issue when resolving external domain names (`Resolving www.google.com... failed: Connection timed out.`)

But the PR looks better now, thanks @borisroman for picking it up.

**Comment by miguelaferreira** [comment]
go build

**Comment by miguelaferreira** [comment]
go build

**Comment by borisroman** [comment]
go build

**Pull request merged**
