### PR TITLE
DB cleanups and optimisations

### PR DESCRIPTION
**Pull request by remibergsma**
Backport of PR 1466 of ACS

### CODE REVIEW

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
@remibergsma Please move DB upgrades from 510-511 to 511-520.

**Comment by remibergsma** [comment]
@borisroman done, also rebased with latest master

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Comment by remibergsma** [comment]
go build

**Pull request merged**
