### PR TITLE
[WIP] Gui modifications

### PR DESCRIPTION
**Pull request by sanderv32**
Small fixes are:
- Disabled infinite scroll in HA worker list
- Fixed loading pane on whohasthisip/mac

Major improvements:

- Use migration dialog of instances also for storage
**Before:**
image
**After:**
image

- Show volume state
image

### CODE REVIEW

**Comment by remibergsma** [comment]
@sanderv32 Can you please squash your changes (or at least cleanup the commits a bit, remove the merges/rebases etc). What else needs to be done before this is ready? Looks nice!

**Comment by sanderv32** [comment]
@remibergsma Did the cleanup and testing the feature seems to work.. Can you have a look so that we can remove the WIP of this branch?

**Comment by remibergsma** [comment]
go build

**Comment by borisroman** [comment]
go build

**Comment by sanderv32** [comment]
go build

**Pull request closed without merging**
